import { ArrowRight, Check, CircleDollarSign, LockKeyhole, MapPinned, Route, ShieldCheck, Sparkles, Users, Wrench } from "lucide-react";

import { BrandMark } from "@/components/BrandMark";

const plans = [
  { name: "Starter", price: "₹2,999", suffix: "/ month", note: "For focused fleet teams", vehicles: "3 vehicles included", overage: "₹500 per additional vehicle", accent: "sand" },
  { name: "Growth", price: "₹9,999", suffix: "/ month", note: "For growing operators", vehicles: "15 vehicles included", overage: "₹450 per additional vehicle", accent: "orange", featured: true },
  { name: "Scale", price: "₹24,999", suffix: "/ month", note: "For multi-depot operations", vehicles: "50 vehicles included", overage: "₹350 per additional vehicle", accent: "ink" },
  { name: "Enterprise", price: "Custom", suffix: " pricing", note: "For large transport networks", vehicles: "100+ vehicles included", overage: "₹300 per additional vehicle", accent: "green" },
];

export function MarketingNav({ active }: { active?: string }) {
  return <header className="marketing-nav"><a className="brand-lockup" href="/"><BrandMark decorative className="marketing-brand-mark" /><span><strong>VahanSync</strong><small>Fleet intelligence for India’s operators</small></span></a><nav className="marketing-links" aria-label="Public navigation"><a className={active === "pricing" ? "active" : ""} href="/pricing">Pricing</a><a className={active === "about" ? "active" : ""} href="/about">About</a><a className={active === "security" ? "active" : ""} href="/security">Security</a></nav><div className="marketing-actions"><a className="secondary-button" href="/login">Sign in</a><a className="primary-button" href="/create-organization">Create organization <ArrowRight size={15} /></a></div></header>;
}

export function MarketingFooter() {
  return <footer className="marketing-footer"><div><a className="brand-lockup" href="/"><BrandMark decorative className="marketing-brand-mark is-small" /><span><strong>VahanSync</strong><small>Fleet intelligence for India’s operators</small></span></a><p>Connected fleet operations for India’s transport organizations.</p></div><div className="footer-links"><a href="/pricing">Pricing</a><a href="/about">About</a><a href="/security">Security</a><a href="/login">Sign in</a></div><small>© {new Date().getFullYear()} VahanSync. Built for accountable operations.</small></footer>;
}

export function PricingPage() {
  return <main className="marketing-page"><MarketingNav active="pricing" /><section className="marketing-hero compact"><div className="marketing-kicker"><span /> Clear pricing for connected operations</div><h1>Scale your fleet without losing the <em>operating picture.</em></h1><p>Start with a predictable platform fee, pay for the active vehicles you actually manage, and keep every team member inside the right operational boundary.</p><div className="marketing-hero-actions"><a className="primary-button" href="/create-organization">Start 14-day trial <ArrowRight size={16} /></a><a className="text-link" href="/login">Already have access? Sign in <ArrowRight size={15} /></a></div></section><section className="pricing-grid">{plans.map((plan) => <article className={`pricing-card ${plan.accent} ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured && <span className="pricing-badge">Most chosen</span>}<div className="pricing-card-top"><span>{plan.name}</span><CircleDollarSign size={17} /></div><p>{plan.note}</p><div className="pricing-amount">{plan.price}<small>{plan.suffix}</small></div><div className="pricing-divider" /><div className="pricing-feature"><Check size={15} /> {plan.vehicles}</div><div className="pricing-feature"><Check size={15} /> {plan.overage}</div><div className="pricing-feature"><Check size={15} /> All role workspaces and core workflows</div><a className={plan.featured ? "primary-button" : "secondary-button"} href="/create-organization">Choose {plan.name} <ArrowRight size={14} /></a></article>)}</section><section className="pricing-note"><div><div className="marketing-kicker"><span /> The VahanSync principle</div><h2>One bill for the organization. The right view for every role.</h2></div><p>Billing is organization-owned and separate from operational permissions. During trial and payment grace, your historical records and exports remain available; operational writes are only restricted when an account is formally suspended.</p></section><MarketingFooter /></main>;
}

export function AboutPage() {
  return <main className="marketing-page"><MarketingNav active="about" /><section className="marketing-hero split"><div><div className="marketing-kicker"><span /> About VahanSync</div><h1>The operating layer between a vehicle’s <em>next route</em> and its next repair.</h1></div><p className="hero-aside">VahanSync is built for transport organizations that need readiness, maintenance, inventory, safety, and finance to move together—not live in disconnected spreadsheets and inboxes.</p></section><section className="about-story"><div className="story-stamp"><Sparkles size={18} /><span>Built for the real handoff</span></div><div className="story-copy"><p>Every fleet has a chain of responsibility. A driver notices an issue. A Fleet Manager decides what happens next. A mechanic executes the work. Inventory supplies the part. Accounting closes the cost. VahanSync gives that chain one shared record while keeping each workspace focused.</p><p>Our product philosophy is simple: make the next responsible action obvious, keep the source data close to the decision, and make every handoff auditable.</p></div></section><section className="about-pillars"><article><span><Wrench size={19} /></span><h3>Operationally grounded</h3><p>Designed around vehicles, odometer readings, component life, work orders, parts, and proof of work.</p></article><article><span><Users size={19} /></span><h3>Connected by default</h3><p>One organization shares one operational truth, while role boundaries keep sensitive work appropriately scoped.</p></article><article><span><MapPinned size={19} /></span><h3>Made for India</h3><p>INR-native records, Indian number formatting, and workflows that fit growing bus and commercial fleet operators.</p></article></section><section className="about-cta"><div><div className="marketing-kicker"><span /> Start with clarity</div><h2>Bring the whole operating chain into focus.</h2></div><a className="primary-button" href="/create-organization">Create your organization <ArrowRight size={16} /></a></section><MarketingFooter /></main>;
}

export function SecurityPage() {
  const controls = ["Organization-scoped data access", "Role-aware server procedures", "Supabase Auth session handling", "Audit trails for operational actions", "Controlled document and evidence access", "Export permissions with filter context"];
  return <main className="marketing-page"><MarketingNav active="security" /><section className="marketing-hero compact"><div className="marketing-kicker"><span /> Security and control</div><h1>Trust the system with the <em>right boundaries.</em></h1><p>VahanSync is designed so a connected organization can collaborate without turning every workspace into an unrestricted control panel.</p></section><section className="security-layout"><div className="security-intro"><span className="security-icon"><ShieldCheck size={22} /></span><h2>Designed for accountable access.</h2><p>VahanSync combines Supabase authentication, tenant-scoped server procedures, workspace-level navigation, and auditable operational actions. Security is treated as part of the workflow, not a page hidden in settings.</p><a className="text-link" href="/create-organization">Build your workspace <ArrowRight size={15} /></a></div><div className="security-controls">{controls.map((control, index) => <div className="security-control" key={control}><span>0{index + 1}</span><strong>{control}</strong><Check size={15} /></div>)}</div></section><section className="security-callout"><LockKeyhole size={19} /><div><strong>Clear ownership, durable records.</strong><p>Organization owners govern membership and billing. Operators see only the work their role requires. Historical records remain available for review and export according to permission.</p></div></section><MarketingFooter /></main>;
}
