import { useEffect, useState } from "react";
import { Check, CircleAlert, Cloud, CloudOff, Gauge, Plus, Route, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { WorkspaceState as State } from "@/components/workspaces/WorkspaceState";
import type { FleetVehicle, FuelLogRow, InspectionRow, NotificationRow, VehicleIssueRow } from "@/types/fleet";

export function DriverWorkspace() {
  const utils = trpc.useUtils();
  const vehicles = trpc.vehicles.list.useQuery(undefined, { retry: false });
  const dailyHome = trpc.driver.dailyHome.useQuery(undefined, { retry: false });
  const [vehicleId, setVehicleId] = useState("");
  const safeVehicles = dailyHome.data?.vehicle ? [dailyHome.data.vehicle] : vehicles.data?.filter((vehicle: FleetVehicle) => vehicle?.id && vehicle.licensePlate).slice(0, 1) ?? [];
  useEffect(() => { if (vehicleId || !safeVehicles.length) return; setVehicleId(safeVehicles[0].id); }, [safeVehicles, vehicleId]);
  const inspections = trpc.driver.inspections.useQuery(undefined, { retry: false });
  const fuelLogs = trpc.driver.fuelLogs.useQuery(undefined, { retry: false });
  const issues = trpc.vehicleIssues.list.useQuery(undefined, { retry: false });
  const notifications = trpc.notifications.list.useQuery(undefined, { retry: false });
  const [inspectionType, setInspectionType] = useState<"PRE_TRIP" | "POST_TRIP">("PRE_TRIP");
  const [inspectionStatus, setInspectionStatus] = useState<"PASS" | "FAIL">("PASS");
  const [inspectionNotes, setInspectionNotes] = useState(""); const [photoData, setPhotoData] = useState(""); const [manualOdometer, setManualOdometer] = useState(""); const [receiptData, setReceiptData] = useState(""); const [liters, setLiters] = useState(""); const [amount, setAmount] = useState(""); const [odometer, setOdometer] = useState(""); const [station, setStation] = useState(""); const [issueTitle, setIssueTitle] = useState(""); const [issueDescription, setIssueDescription] = useState(""); const [issuePriority, setIssuePriority] = useState<"LOW" | "MEDIUM" | "HIGH" | "CRITICAL">("MEDIUM"); const [issuePhoto, setIssuePhoto] = useState(""); const [issueDraftHydrated, setIssueDraftHydrated] = useState(false); const [issueDraftStatus, setIssueDraftStatus] = useState<"saved" | "offline">("saved"); const [dispositionNotes, setDispositionNotes] = useState("");
  useEffect(() => { try { const raw = localStorage.getItem("fleetops:driver-issue-draft"); if (raw) { const draft = JSON.parse(raw); setVehicleId(draft.vehicleId ?? ""); setIssueTitle(draft.issueTitle ?? ""); setIssueDescription(draft.issueDescription ?? ""); setIssuePriority(draft.issuePriority ?? "MEDIUM"); setIssuePhoto(draft.issuePhoto ?? ""); } } catch { /* ignore malformed local drafts */ } finally { setIssueDraftHydrated(true); } }, []);
  useEffect(() => { if (!issueDraftHydrated) return; const hasDraft = Boolean(issueTitle.trim() || issueDescription.trim() || issuePhoto); if (!hasDraft) { localStorage.removeItem("fleetops:driver-issue-draft"); return; } localStorage.setItem("fleetops:driver-issue-draft", JSON.stringify({ vehicleId, issueTitle, issueDescription, issuePriority, issuePhoto })); setIssueDraftStatus(navigator.onLine ? "saved" : "offline"); }, [issueDraftHydrated, vehicleId, issueTitle, issueDescription, issuePriority, issuePhoto]);
  const createInspection = trpc.driver.createInspection.useMutation({ onSuccess: () => { setInspectionNotes(""); setPhotoData(""); toast.success("DVIR inspection submitted"); void utils.driver.inspections.invalidate(); }, onError: (error) => toast.error("DVIR submission failed", { description: error.message }) });
  const updateOdometer = trpc.vehicles.updateOdometer.useMutation({ onSuccess: async ({ vehicle, odometerLog }) => { setManualOdometer(""); toast.success("Odometer updated", { description: `${Number(odometerLog.reading).toLocaleString("en-IN")} km saved for ${vehicle.licensePlate}.` }); await Promise.all([utils.vehicles.list.invalidate(), utils.driver.dailyHome.invalidate(), dailyHome.refetch()]); }, onError: (error) => toast.error("Odometer update rejected", { description: error.message }) });
  const createFuel = trpc.driver.createFuelLog.useMutation({ onSuccess: () => { setLiters(""); setAmount(""); setOdometer(""); setStation(""); setReceiptData(""); toast.success("Fuel log saved"); void utils.driver.fuelLogs.invalidate(); void utils.vehicles.list.invalidate(); }, onError: (error) => toast.error("Fuel log failed", { description: error.message }) });
  const createIssue = trpc.vehicleIssues.create.useMutation({ onSuccess: () => { setIssueTitle(""); setIssueDescription(""); setIssuePriority("MEDIUM"); setIssuePhoto(""); localStorage.removeItem("fleetops:driver-issue-draft"); setIssueDraftStatus("saved"); toast.success("Vehicle issue sent to Fleet Manager"); void utils.vehicleIssues.list.invalidate(); void utils.notifications.list.invalidate(); void dailyHome.refetch(); }, onError: (error) => toast.error("Issue report failed", { description: error.message }) });
  const unsafeDisposition = trpc.driver.unsafeDisposition.useMutation({ onSuccess: () => { setDispositionNotes(""); toast.success("Vehicle safety disposition recorded"); void dailyHome.refetch(); void utils.vehicles.list.invalidate(); void utils.notifications.list.invalidate(); }, onError: (error) => toast.error("Safety disposition failed", { description: error.message }) });
  const readPhoto = (file: File | undefined, setter: (value: string) => void) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setter(String(reader.result)); reader.readAsDataURL(file); };
  const readinessLabel = dailyHome.data?.readiness ?? "CHECKING"; const assignedVehicle = dailyHome.data?.vehicle?.licensePlate ?? safeVehicles[0]?.licensePlate ?? "No assignment"; const currentReading = Number(dailyHome.data?.vehicle?.currentOdometer ?? safeVehicles[0]?.currentOdometer ?? 0);
  const vehicleSelect = (label: string) => <label>{label}<select required value={vehicleId} onChange={(event) => setVehicleId(event.target.value)}><option value="">Select vehicle</option>{safeVehicles.map((vehicle: FleetVehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.licensePlate} · {vehicle.make} {vehicle.model}</option>)}</select></label>;

  return <main className="replacement-driver-shift">
    <header className="replacement-driver-hero"><div><span>Driver workspace · shift safety</span><h1>Start with the vehicle condition, not the route<em>.</em></h1><p>Complete safety handoffs, maintain a trusted odometer reading, report risks early, and leave a connected operational record.</p></div><div className="replacement-driver-hero-chip"><Route size={20} /><strong>{assignedVehicle}</strong><small>assigned fleet vehicle</small></div></header>
    <section className="driver-signal-strip replacement-driver-signals" aria-label="Driver readiness summary"><article><Route size={17} /><span>Assigned vehicle</span><strong>{assignedVehicle}</strong><small>{dailyHome.data?.vehicle ? "organization assignment" : "waiting for Fleet Manager"}</small></article><article className={readinessLabel === "READY" ? "is-safe" : "is-alert"}>{readinessLabel === "READY" ? <ShieldCheck size={17} /> : <CircleAlert size={17} />}<span>Readiness</span><strong>{readinessLabel}</strong><small>start-of-shift signal</small></article><article><Gauge size={17} /><span>Current odometer</span><strong>{currentReading.toLocaleString("en-IN")} km</strong><small>persisted fleet reading</small></article><article className={issueDraftStatus === "offline" ? "is-alert" : "is-safe"}>{issueDraftStatus === "offline" ? <CloudOff size={17} /> : <Cloud size={17} />}<span>Issue draft</span><strong>{issueDraftStatus === "offline" ? "Offline saved" : "Synced"}</strong><small>local safe draft</small></article></section>
    <section className="replacement-driver-readiness"><div><span>01 · Start-of-shift daily home</span><h2>Vehicle readiness: {dailyHome.isLoading ? "Loading…" : readinessLabel}</h2><p>{dailyHome.data?.nextAction ?? "Your assigned vehicle readiness will appear here."}</p></div>{dailyHome.data?.vehicle && <form onSubmit={(event) => { event.preventDefault(); if (dispositionNotes.trim()) unsafeDisposition.mutate({ vehicleId: dailyHome.data.vehicle.id, disposition: readinessLabel === "UNSAFE" ? "CLEARED_TO_DRIVE" : "UNSAFE_TO_DRIVE", notes: dispositionNotes }); }}><label>Safety disposition note<textarea required minLength={3} maxLength={1000} value={dispositionNotes} onChange={(event) => setDispositionNotes(event.target.value)} placeholder="Explain the defect or why the vehicle is cleared." /></label><button className="replacement-driver-secondary" disabled={unsafeDisposition.isPending}>{unsafeDisposition.isPending ? "Recording…" : readinessLabel === "UNSAFE" ? "Request clearance" : "Mark unsafe and alert Fleet Manager"}</button></form>}</section>
    <section className="replacement-driver-actions">
      <form onSubmit={(event) => { event.preventDefault(); if (vehicleId && manualOdometer.trim()) updateOdometer.mutate({ vehicleId, reading: Number(manualOdometer), source: "MANUAL_DRIVER" }); }}><header><Gauge size={18} /><div><span>Driver telematics</span><h2>Manual odometer</h2></div></header><p>Verified reading is persisted to the organization vehicle record. Rollbacks and implausible distance changes are rejected.</p>{vehicleSelect("Vehicle")}<label>Odometer (km)<input required type="number" min={String(Math.max(0, Number(safeVehicles.find((vehicle: FleetVehicle) => vehicle.id === vehicleId)?.latestOdometerReading ?? safeVehicles.find((vehicle: FleetVehicle) => vehicle.id === vehicleId)?.currentOdometer ?? 0)))} step="1" value={manualOdometer} onChange={(event) => setManualOdometer(event.target.value)} /></label><button className="replacement-driver-primary" disabled={updateOdometer.isPending || vehicles.isLoading}>{updateOdometer.isPending ? "Updating…" : "Submit odometer"}</button></form>
      <form onSubmit={(event) => { event.preventDefault(); if (vehicleId) createInspection.mutate({ vehicleId, inspectionType, status: inspectionStatus, notes: inspectionNotes || undefined, photoData: photoData || undefined }); }}><header><Check size={18} /><div><span>Driver safety workflow</span><h2>DVIR inspection</h2></div></header><p>Complete pre-trip or post-trip evidence before leaving the depot. Failed inspections remain visible to the fleet team.</p>{vehicleSelect("Vehicle")}<label>Inspection type<select value={inspectionType} onChange={(event) => setInspectionType(event.target.value as typeof inspectionType)}><option value="PRE_TRIP">Pre-trip</option><option value="POST_TRIP">Post-trip</option></select></label><label>Result<select value={inspectionStatus} onChange={(event) => setInspectionStatus(event.target.value as typeof inspectionStatus)}><option value="PASS">Pass</option><option value="FAIL">Fail</option></select></label><label>Notes<textarea value={inspectionNotes} onChange={(event) => setInspectionNotes(event.target.value)} placeholder="Record defects or observations" /></label><label>Photo proof<input type="file" accept="image/*" onChange={(event) => readPhoto(event.target.files?.[0], setPhotoData)} /></label><button className="replacement-driver-primary" disabled={createInspection.isPending || vehicles.isLoading}>{createInspection.isPending ? "Submitting…" : "Submit inspection"}</button></form>
      <form onSubmit={(event) => { event.preventDefault(); if (vehicleId) createIssue.mutate({ vehicleId, title: issueTitle, description: issueDescription, priority: issuePriority, photoData: issuePhoto || undefined, photoContentType: issuePhoto ? "image/jpeg" : undefined }); }}><header><CircleAlert size={18} /><div><span>Driver safety escalation</span><h2>Report vehicle issue</h2></div></header><p>Send a defect or breakdown report directly to Fleet Manager. The draft remains locally available if connectivity drops.</p>{vehicleSelect("Vehicle")}<label>Issue title<input required minLength={3} maxLength={160} value={issueTitle} onChange={(event) => setIssueTitle(event.target.value)} placeholder="Brake warning light" /></label><label>Urgency<select value={issuePriority} onChange={(event) => setIssuePriority(event.target.value as typeof issuePriority)}>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((item) => <option key={item}>{item}</option>)}</select></label><label>What happened?<textarea required minLength={5} maxLength={4000} value={issueDescription} onChange={(event) => setIssueDescription(event.target.value)} placeholder="Describe the defect, symptoms, and whether the vehicle is safe to operate." /></label><label>Photo evidence<input type="file" accept="image/*" onChange={(event) => readPhoto(event.target.files?.[0], setIssuePhoto)} /></label><small className="workspace-draft-status">{issueDraftStatus === "offline" ? "Offline draft saved locally; send when connectivity returns." : "Draft saved locally while you work."}</small><button className="replacement-driver-primary" disabled={createIssue.isPending || vehicles.isLoading}>{createIssue.isPending ? "Sending…" : "Send issue report"}</button></form>
      <form onSubmit={(event) => { event.preventDefault(); if (vehicleId) createFuel.mutate({ vehicleId, liters: Number(liters), amount: Number(amount), odometer: Number(odometer), station: station || undefined, receiptData: receiptData || undefined }); }}><header><Plus size={18} /><div><span>Fuel and odometer</span><h2>Log a fill-up</h2></div></header><p>Fuel entries update the vehicle odometer and enter the accountant cost metrics with station and receipt evidence.</p><label>Liters<input required type="number" min="0.1" step="0.1" value={liters} onChange={(event) => setLiters(event.target.value)} /></label><label>Amount (₹)<input required type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Odometer (km)<input required type="number" min="0" step="1" value={odometer} onChange={(event) => setOdometer(event.target.value)} /></label><label>Station<input value={station} onChange={(event) => setStation(event.target.value)} placeholder="Fuel station" /></label><label>Receipt photo<input type="file" accept="image/*" onChange={(event) => readPhoto(event.target.files?.[0], setReceiptData)} /></label><button className="replacement-driver-primary" disabled={createFuel.isPending || vehicles.isLoading}>{createFuel.isPending ? "Saving…" : "Save fuel log"}</button></form>
    </section>
    <section className="replacement-driver-history"><article><header><span>Issue history</span><h2>Reported vehicle issues</h2></header><State loading={issues.isLoading} error={issues.isError} empty={!issues.isLoading && !issues.isError && !issues.data?.length}><div>{(issues.data ?? []).filter((item: VehicleIssueRow) => item?.id).map((item: VehicleIssueRow) => <div key={item.id}><strong>{item.title}</strong><p>{item.priority} · {item.status} · {item.description} · {(() => { const response = (notifications.data ?? []).find((note: NotificationRow) => note.referenceId === item.id); return response ? `${response.acknowledgedAt ? "Acknowledged" : "Submitted"}${response.escalationLevel ? ` · Escalation ${response.escalationLevel}` : ""}${response.resolvedAt ? " · Resolved" : ""}` : "Awaiting Fleet Manager response"; })()}</p><b>{new Date(item.createdAt).toLocaleString("en-IN")}</b></div>)}</div></State></article><article><header><span>Driver history</span><h2>Recent inspections</h2></header><State loading={inspections.isLoading} error={inspections.isError} empty={!inspections.isLoading && !inspections.isError && !inspections.data?.length}><div>{(inspections.data ?? []).filter((item: InspectionRow) => item?.id).map((item: InspectionRow) => <div key={item.id}><strong>{item.inspectionType.replace("_", " ")}</strong><p>{item.status} · {item.notes ?? "No notes"}</p><b>{new Date(item.createdAt).toLocaleString("en-IN")}</b></div>)}</div></State></article><article><header><span>Fuel history</span><h2>Recent fill-ups</h2></header><State loading={fuelLogs.isLoading} error={fuelLogs.isError} empty={!fuelLogs.isLoading && !fuelLogs.isError && !fuelLogs.data?.length}><div>{(fuelLogs.data ?? []).filter((item: FuelLogRow) => item?.id).map((item: FuelLogRow) => <div key={item.id}><strong>{Number(item.liters).toLocaleString("en-IN")} L · ₹{Number(item.amount).toLocaleString("en-IN")}</strong><p>{item.station ?? "Station not recorded"}</p><b>{Number(item.odometer).toLocaleString("en-IN")} km</b></div>)}</div></State></article></section>
  </main>;
}
