import { useMemo, useState } from "react";
import { Activity, Check, ShieldCheck, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import type { AuditEvent, DocumentRow, NotificationRow } from "@/types/fleet";
import { WorkspaceState as State } from "@/components/workspaces/WorkspaceState";

export function ExecutiveOverviewWorkspace({ organizationName }: { organizationName?: string }) {
  const summary = trpc.dashboard.summary.useQuery(undefined, { retry: false }); const metrics = trpc.financials.metrics.useQuery(undefined, { retry: false }); const members = trpc.team.members.useQuery(undefined, { retry: false }); const notifications = trpc.notifications.list.useQuery(undefined, { retry: false }); const documents = trpc.documents.list.useQuery(undefined, { retry: false }); const [auditFilters, setAuditFilters] = useState({ actorRole: "", entityType: "", action: "", outcome: "", dateFrom: "", dateTo: "" });
  const auditInput = useMemo(() => ({ limit: 100, ...(auditFilters.actorRole ? { actorRole: auditFilters.actorRole } : {}), ...(auditFilters.entityType ? { entityType: auditFilters.entityType } : {}), ...(auditFilters.action ? { action: auditFilters.action } : {}), ...(auditFilters.outcome ? { outcome: auditFilters.outcome as "SUCCESS" | "ERROR" } : {}), ...(auditFilters.dateFrom ? { dateFrom: new Date(`${auditFilters.dateFrom}T00:00:00.000Z`).toISOString() } : {}), ...(auditFilters.dateTo ? { dateTo: new Date(`${auditFilters.dateTo}T23:59:59.999Z`).toISOString() } : {}) }), [auditFilters]);
  const audit = trpc.audit.list.useQuery(auditInput, { retry: false }); const unread = notifications.data?.filter((item: NotificationRow) => !item.isRead).length ?? 0; const expiring = documents.data?.filter((item: DocumentRow) => new Date(item.expiryDate).getTime() < Date.now() + 30 * 86400000).length ?? 0;
  return <main className="replacement-executive-overview"><header className="replacement-executive-hero"><div><span>Super Admin / Owner · organization governance</span><h1>See the whole operation without entering its role workspaces<em>.</em></h1><p>{organizationName ?? "Your organization"} governance combines operating signals, role coverage, financial position, compliance exposure, and an immutable organization audit trail.</p></div><div className="replacement-executive-hero-chip"><ShieldCheck size={20} /><strong>{summary.data?.vehicles?.length ?? 0}</strong><small>organization vehicles</small></div></header>
    <section className="replacement-executive-signals" aria-label="Organization governance summary"><article><Activity size={17} /><span>Open maintenance</span><strong>{summary.data?.openWorkOrders ?? 0}</strong><small>orders needing control</small></article><article className={unread ? "is-alert" : "is-safe"}><Check size={17} /><span>Unread alerts</span><strong>{unread}</strong><small>recipient-scoped signals</small></article><article className={expiring ? "is-alert" : "is-safe"}><ShieldCheck size={17} /><span>30-day compliance</span><strong>{expiring}</strong><small>documents needing review</small></article><article><UsersRound size={17} /><span>Role coverage</span><strong>{members.data?.length ?? 0}</strong><small>connected members</small></article></section>
    <section className="replacement-executive-grid"><article className="replacement-executive-pulse"><header><div><span>01 · organization pulse</span><h2>Operating boundaries</h2></div><b>Governance only</b></header><div><article><strong>{members.data?.length ?? 0} connected members</strong><p>Every member is restricted to their organization and their assigned operating workspace.</p></article><article><strong>{summary.data?.org?.subscriptionTier?.replaceAll("_", " ") ?? "Trial plan"}</strong><p>Billing capacity and organization configuration remain Super Admin / Owner controls.</p></article><article><strong>RLS and procedure guards active</strong><p>Tenant and role checks remain enforced server-side for every protected request.</p></article></div></article><article className="replacement-executive-finance"><header><div><span>02 · global P&amp;L</span><h2>INR position</h2></div><b>Read only</b></header><div><article><span>Revenue</span><strong>₹{Number(metrics.data?.totals?.revenue ?? 0).toLocaleString("en-IN")}</strong></article><article><span>Expenses</span><strong>₹{Number(metrics.data?.totals?.expenses ?? 0).toLocaleString("en-IN")}</strong></article><article><span>Profit</span><strong>₹{Number(metrics.data?.totals?.profit ?? 0).toLocaleString("en-IN")}</strong></article></div></article></section>
    <section className="replacement-executive-alerts"><header><div><span>03 · oversight queue</span><h2>Recent organization alerts</h2></div><b>{unread} unread</b></header><State loading={notifications.isLoading} error={notifications.isError} empty={!notifications.isLoading && !notifications.isError && !notifications.data?.length}><div>{notifications.data?.slice(0, 6).map((item: NotificationRow) => <article key={item.id}><div><strong>{item.title}</strong><p>{item.message}</p></div><b className={item.isRead ? "is-safe" : "is-alert"}>{item.isRead ? "Read" : "Review"}</b></article>)}</div></State></section>
    <section className="replacement-executive-audit"><header><div><span>04 · governance history</span><h2>Searchable audit log</h2></div><button type="button" className="replacement-executive-secondary" onClick={() => setAuditFilters({ actorRole: "", entityType: "", action: "", outcome: "", dateFrom: "", dateTo: "" })}>Clear filters</button></header><div className="replacement-executive-filters audit-filter-grid"><label>Role<select aria-label="Filter audit by actor role" value={auditFilters.actorRole} onChange={(event) => setAuditFilters((current) => ({ ...current, actorRole: event.target.value }))}><option value="">All roles</option><option value="SUPERADMIN">Super Admin / Owner</option><option value="FLEET_MANAGER">Fleet Manager</option><option value="INVENTORY_MANAGER">Inventory Manager</option><option value="MECHANIC">Mechanic</option><option value="TECHNICIAN">Technician</option><option value="DRIVER">Driver</option><option value="ACCOUNTANT">Accountant</option></select></label><label>Entity<input aria-label="Filter audit by entity" placeholder="e.g. WORK_ORDER" value={auditFilters.entityType} onChange={(event) => setAuditFilters((current) => ({ ...current, entityType: event.target.value.toUpperCase() }))} /></label><label>Action<input aria-label="Filter audit by action" placeholder="e.g. WORK_ORDER_CREATED" value={auditFilters.action} onChange={(event) => setAuditFilters((current) => ({ ...current, action: event.target.value.toUpperCase() }))} /></label><label>Outcome<select aria-label="Filter audit by outcome" value={auditFilters.outcome} onChange={(event) => setAuditFilters((current) => ({ ...current, outcome: event.target.value }))}><option value="">All outcomes</option><option value="SUCCESS">Success</option><option value="ERROR">Error</option></select></label><label>From<input aria-label="Filter audit from date" type="date" value={auditFilters.dateFrom} onChange={(event) => setAuditFilters((current) => ({ ...current, dateFrom: event.target.value }))} /></label><label>To<input aria-label="Filter audit to date" type="date" value={auditFilters.dateTo} onChange={(event) => setAuditFilters((current) => ({ ...current, dateTo: event.target.value }))} /></label></div><State loading={audit.isLoading} error={audit.isError} empty={!audit.isLoading && !audit.isError && !audit.data?.length}><div className="replacement-executive-audit-rows">{audit.data?.map((item: AuditEvent) => <article key={item.id}><div><strong>{item.summary}</strong><p>{item.actorRole ?? "System"} · {item.action} · {item.entityType} · {new Date(item.createdAt).toLocaleString("en-IN")}</p></div><b>Logged</b></article>)}</div></State></section>
  </main>;
}
