import { useEffect, useState } from "react";
import { Activity, Clock3, Copy, Mail, RefreshCw, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import type { Invitation, InvitationResponse, TeamMember } from "@/types/fleet";

const roleOptions = ["FLEET_MANAGER", "MECHANIC", "TECHNICIAN", "DRIVER", "INVENTORY_MANAGER", "ACCOUNTANT"] as const;
const roleLabel = (role: string) => role === "SUPERADMIN" ? "Super Admin / Owner" : role.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const invitationLink = (value?: string) => {
  if (!value) return "";
  return value.startsWith("http") ? value : new URL(value, window.location.origin).toString();
};
function State({ loading, error, empty, children }: { loading?: boolean; error?: boolean; empty?: boolean; children: React.ReactNode }) { if (loading) return <div className="workspace-state"><RefreshCw className="spin" size={18} /> Loading live VahanSync data…</div>; if (error) return <div className="workspace-state error-state">This workspace could not load from Supabase. Check your session and try again.</div>; if (empty) return <div className="workspace-state">No records yet. Use the action above to create the first record.</div>; return <>{children}</>; }

export function TeamWorkspace({ enabled }: { enabled: boolean }) {
  const utils = trpc.useUtils(); const members = trpc.team.members.useQuery(undefined, { enabled, retry: false }); const invitations = trpc.team.invitations.useQuery(undefined, { enabled, retry: false }); const [email, setEmail] = useState(""); const [role, setRole] = useState<(typeof roleOptions)[number]>("FLEET_MANAGER"); const [lastInvitation, setLastInvitation] = useState<InvitationResponse | null>(null); const [inviteStartedAt, setInviteStartedAt] = useState<number | null>(null); const [inviteTimedOut, setInviteTimedOut] = useState(false);
  const invite = trpc.team.invite.useMutation({ onSuccess: (data) => { setLastInvitation(data); setInviteStartedAt(null); setInviteTimedOut(false); setEmail(""); toast.success("Invitation saved", { description: "No email provider is configured; send the redeemable token below to the teammate." }); void utils.team.members.invalidate(); void utils.team.invitations.invalidate(); }, onError: (error) => { setInviteStartedAt(null); setInviteTimedOut(false); toast.error("Invitation failed", { description: error.message }); } });
  const resendInvitation = trpc.team.resendInvitation.useMutation({ onSuccess: (data) => { setLastInvitation(data); toast.success("Invitation resent", { description: data.delivery === "EMAIL" ? "A fresh Join Organization link was emailed." : "Share the refreshed Join Organization link below." }); void utils.team.invitations.invalidate(); }, onError: (error) => toast.error("Invitation resend failed", { description: error.message }) });
  const revokeInvitation = trpc.team.revokeInvitation.useMutation({ onSuccess: () => { toast.success("Invitation revoked"); void utils.team.invitations.invalidate(); }, onError: (error) => toast.error("Invitation revoke failed", { description: error.message }) }); const updateRole = trpc.team.updateRole.useMutation({ onSuccess: () => { toast.success("Role updated"); void utils.team.members.invalidate(); }, onError: (error) => toast.error("Role update failed", { description: error.message }) }); const removeMember = trpc.team.removeMember.useMutation({ onSuccess: () => { toast.success("Member removed", { description: "The organization membership and Auth identity were deleted." }); void utils.team.members.invalidate(); void utils.team.invitations.invalidate(); }, onError: (error) => toast.error("Member removal failed", { description: error.message }) });
  useEffect(() => { if (!invite.isPending || !inviteStartedAt) return; const timer = window.setTimeout(() => { setInviteTimedOut(true); toast.error("Invitation request timed out", { description: "The database did not respond. You can retry without leaving Team." }); }, 10_000); return () => window.clearTimeout(timer); }, [invite.isPending, inviteStartedAt]);
  const invitationRows = invitations.data ?? []; const invitationStatus = invitationRows.reduce((counts: Record<string, number>, item: Invitation) => { const status = item.acceptedAt ? "accepted" : item.revokedAt ? "revoked" : new Date(item.expiresAt) < new Date() ? "expired" : "pending"; counts[status] = (counts[status] ?? 0) + 1; return counts; }, {}); const acceptedCount = invitationStatus.accepted ?? 0; const pendingCount = invitationStatus.pending ?? 0; const activeRoles = new Set((members.data ?? []).map((member: TeamMember) => member.role)).size;
  return <main className="replacement-team-governance"><header className="replacement-team-hero"><div><span>Team access · organization governance</span><h1>Give each operator the smallest role that gets work done<em>.</em></h1><p>Invite, review, update, and revoke access with a live directory and invitation evidence inside the active organization.</p></div><div className="replacement-team-hero-chip"><UsersRound size={20} /><strong>{members.data?.length ?? 0}</strong><small>organization members</small></div></header>
    <section className="governance-signal-grid replacement-team-signals" aria-label="Team governance summary"><article><UsersRound size={17} /><span>Organization members</span><strong>{members.data?.length ?? 0}</strong><small>live directory</small></article><article><Mail size={17} /><span>Invitation health</span><strong>{pendingCount}</strong><small>{acceptedCount} accepted</small></article><article><Activity size={17} /><span>Role coverage</span><strong>{activeRoles}/7</strong><small>assigned roles</small></article><article><Clock3 size={17} /><span>Access rhythm</span><strong>7 days</strong><small>invitation expiry</small></article></section>
    <section className="replacement-team-invite"><div><span>01 · Team access</span><h2>Invite a teammate</h2><p>Choose the least-privileged role needed for the job. Invitations expire after seven days and retain a deliverable, auditable handoff.</p></div><form onSubmit={(event) => { event.preventDefault(); if (email) { setInviteTimedOut(false); setInviteStartedAt(Date.now()); invite.mutate({ email, role }); } }}><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="teammate@company.com" /></label><label>Role<select value={role} onChange={(event) => setRole(event.target.value as (typeof roleOptions)[number])}>{roleOptions.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><button type="submit" className="replacement-team-primary" disabled={invite.isPending}><UserPlus size={16} />{inviteTimedOut && invite.isPending ? "Waiting for server…" : invite.isPending ? "Creating…" : inviteTimedOut ? "Retry invitation" : "Create invitation"}</button></form>{lastInvitation && <aside className="replacement-team-invite-result"><strong>Invitation link ready to share.</strong><p>{lastInvitation.delivery === "EMAIL" ? `An email was sent to ${lastInvitation.email ?? email}. You can also copy the link below.` : `Copy this secure link and share it directly with ${lastInvitation.email ?? email}.`}</p><div><code>{invitationLink(lastInvitation.joinUrl ?? lastInvitation.tokenHash)}</code><button type="button" className="replacement-team-secondary" onClick={() => { void navigator.clipboard.writeText(invitationLink(lastInvitation.joinUrl ?? lastInvitation.tokenHash)); toast.success("Invite link copied"); }}>Copy invite link</button></div>{lastInvitation.deliveryError && <small className="auth-error">Email delivery: {lastInvitation.deliveryError}</small>}</aside>}</section>
    <section className="replacement-team-directory"><header><div><span>02 · organization directory</span><h2>Members</h2></div><b><ShieldCheck size={14} />RLS protected</b></header><State loading={members.isLoading} error={members.isError} empty={!members.isLoading && !members.isError && !members.data?.length}><div>{members.data?.map((member: TeamMember) => <article key={member.id}><div className="replacement-team-avatar">{String(member.fullName ?? member.email).slice(0, 2).toUpperCase()}</div><div className="replacement-team-member"><strong>{member.fullName ?? "Unnamed member"}</strong><span>{member.email}</span></div><select aria-label={`Role for ${member.fullName ?? member.email}`} value={member.role} disabled={member.role === "SUPERADMIN" || updateRole.isPending || removeMember.isPending} onChange={(event) => updateRole.mutate({ userId: member.id, role: event.target.value as (typeof roleOptions)[number] })}><option value={member.role}>{roleLabel(member.role)}</option>{roleOptions.filter((item) => item !== member.role).map((item) => <option key={item} value={item}>{roleLabel(item)}</option>)}</select>{member.role !== "SUPERADMIN" && <button type="button" className="replacement-team-danger" disabled={removeMember.isPending} onClick={() => { if (window.confirm(`Remove ${member.fullName ?? member.email} from this organization? Their VahanSync membership and Auth account will be deleted.`)) removeMember.mutate({ userId: member.id }); }}>{removeMember.isPending ? "Removing…" : "Remove"}</button>}</article>)}</div></State></section>
    <section className="replacement-team-invitation-ledger"><header><div><span>03 · invitation ledger</span><h2>Invitation status</h2></div><b>{pendingCount} pending · {acceptedCount} accepted · {invitationStatus.expired ?? 0} expired</b></header><State loading={invitations.isLoading} error={invitations.isError} empty={!invitations.isLoading && !invitations.isError && !invitations.data?.length}><div>{invitations.data?.map((row: Invitation) => { const status = row.acceptedAt ? "Accepted" : row.revokedAt ? "Revoked" : new Date(row.expiresAt) < new Date() ? "Expired" : "Pending"; return <article key={row.id}><div><strong>{row.email}</strong><p>{String(row.role).replaceAll("_", " ")} · {new Date(row.expiresAt).toLocaleDateString("en-IN")}</p><code>{row.tokenHash}</code></div><aside>{status === "Pending" && <><button className="replacement-team-secondary" title="Copy invitation token" aria-label="Copy invitation token" onClick={() => { void navigator.clipboard.writeText(row.tokenHash ?? ""); toast.success("Invitation token copied"); }}><Copy size={14} /></button><button type="button" className="replacement-team-secondary" disabled={resendInvitation.isPending} onClick={() => resendInvitation.mutate({ id: row.id })}>{resendInvitation.isPending ? "Resending…" : "Resend"}</button><button type="button" className="replacement-team-danger" disabled={revokeInvitation.isPending} onClick={() => { const reason = window.prompt("Reason for revoking this invitation"); if (reason?.trim()) revokeInvitation.mutate({ id: row.id, reason: reason.trim() }); }}>{revokeInvitation.isPending ? "Revoking…" : "Revoke"}</button></>}<b className={status === "Accepted" ? "is-safe" : status === "Pending" ? "is-pending" : "is-alert"}>{status}</b></aside></article>; })}</div></State></section>
  </main>;
}
