"""add document assets and notifications

Revision ID: 11c49a83d604
Revises: 0fe7d95d408d
Create Date: 2026-09-14 21:37:01.056506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c49a83d604'
down_revision: Union[str, None] = '0fe7d95d408d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('dedupe_key', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_notifications_dedupe_key'), 'operational_notifications', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_operational_notifications_organization_id'), 'operational_notifications', ['organization_id'], unique=False)
    op.create_table('document_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['compliance_documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_document_assets_document_id'), 'document_assets', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_assets_organization_id'), 'document_assets', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_assets_organization_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_document_id'), table_name='document_assets')
    op.drop_table('document_assets')
    op.drop_index(op.f('ix_operational_notifications_organization_id'), table_name='operational_notifications')
    op.drop_index(op.f('ix_operational_notifications_dedupe_key'), table_name='operational_notifications')
    op.drop_table('operational_notifications')
    # ### end Alembic commands ###
