"""add finance telematics and session controls

Revision ID: 3a4f736ac02a
Revises: 11c49a83d604
Create Date: 2026-09-14 21:41:25.049630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4f736ac02a'
down_revision: Union[str, None] = '11c49a83d604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=160), nullable=True),
    sa.Column('fuel_type', sa.String(length=40), nullable=False),
    sa.Column('litres_milli', sa.Integer(), nullable=False),
    sa.Column('price_per_litre_paise', sa.Integer(), nullable=False),
    sa.Column('total_amount_paise', sa.Integer(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('incurred_on', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_transactions_organization_id'), 'fuel_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_vehicle_id'), 'fuel_transactions', ['vehicle_id'], unique=False)
    op.create_table('telematics_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('device_identifier', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telematics_devices_device_identifier'), 'telematics_devices', ['device_identifier'], unique=False)
    op.create_index(op.f('ix_telematics_devices_organization_id'), 'telematics_devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_telematics_devices_vehicle_id'), 'telematics_devices', ['vehicle_id'], unique=False)
    op.create_table('toll_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('toll_operator', sa.String(length=160), nullable=True),
    sa.Column('plaza', sa.String(length=160), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('incurred_on', sa.String(length=20), nullable=False),
    sa.Column('tag_reference', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toll_transactions_organization_id'), 'toll_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_toll_transactions_vehicle_id'), 'toll_transactions', ['vehicle_id'], unique=False)
    op.create_table('telemetry_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=True),
    sa.Column('latitude_e6', sa.Integer(), nullable=True),
    sa.Column('longitude_e6', sa.Integer(), nullable=True),
    sa.Column('speed_kph', sa.Integer(), nullable=True),
    sa.Column('fuel_level_percent', sa.Integer(), nullable=True),
    sa.Column('engine_on', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['telematics_devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_readings_device_id'), 'telemetry_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_organization_id'), 'telemetry_readings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_telemetry_readings_vehicle_id'), 'telemetry_readings', ['vehicle_id'], unique=False)
    with op.batch_alter_table('expenses', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('gst_amount_paise', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('gstin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cost_center', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_expenses_approved_by_users', 'users', ['approved_by'], ['id'])
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    with op.batch_alter_table('expenses', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint('fk_expenses_approved_by_users', type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('cost_center')
        batch_op.drop_column('gstin')
        batch_op.drop_column('gst_amount_paise')
    op.drop_index(op.f('ix_telemetry_readings_vehicle_id'), table_name='telemetry_readings')
    op.drop_index(op.f('ix_telemetry_readings_organization_id'), table_name='telemetry_readings')
    op.drop_index(op.f('ix_telemetry_readings_device_id'), table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_index(op.f('ix_toll_transactions_vehicle_id'), table_name='toll_transactions')
    op.drop_index(op.f('ix_toll_transactions_organization_id'), table_name='toll_transactions')
    op.drop_table('toll_transactions')
    op.drop_index(op.f('ix_telematics_devices_vehicle_id'), table_name='telematics_devices')
    op.drop_index(op.f('ix_telematics_devices_organization_id'), table_name='telematics_devices')
    op.drop_index(op.f('ix_telematics_devices_device_identifier'), table_name='telematics_devices')
    op.drop_table('telematics_devices')
    op.drop_index(op.f('ix_fuel_transactions_vehicle_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_organization_id'), table_name='fuel_transactions')
    op.drop_table('fuel_transactions')
    # ### end Alembic commands ###
